---
- hosts: web
  become: yes

  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
    - "{{ inventory_dir }}/group_vars/secrets.yml"

  pre_tasks:
    - name: Install PHP repository
      apt_repository:
        repo: "ppa:ondrej/php"
        state: present

  roles:
    - { role: common }
    - { role: geerlingguy.php }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.nodejs }
